### ISSUE TITLE
MSX version fonts

### ISSUE THREAD

**Issue by NYYR1KK1** [Fabrizio-Caruso/CROSS-CHASE#21]
In MSX version the fonts are not copied to VRAM that makes this a bit weird looking :)

**Comment by Fabrizio-Caruso** [comment]
@NYYR1KK1 I have just run the game and it looks OK to me.
Could you please describe the exact issue? Which exact binary version have you used?
![msx](https://user-images.githubusercontent.com/29057615/43930097-f5118312-9c37-11e8-832b-6185d34238f6.jpg)

**Comment by Fabrizio-Caruso** [comment]
I copy the fonts into video run in the "redefine" function that you find in:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/cross_lib/display/init_graphics/z88dk/msx/msx_redefined_chars_init_graphics.c

**Comment by Fabrizio-Caruso** [comment]
THANKS A LOT @NYYR1KK1 !
The issue was on just 3 user-defined characters, which on this video mode have to be redefined because each character has an intrinsic color: the same character with a different color has to be handle as two separate characters.

The issue seems now fixed to me. I have uploaded the fixed versions:

https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/FULL_msx_32k.rom
https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/FULL_msx_32k.cas
https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/LIGHT_msx_16k.cas

Could you please tell me if you see any issues?
I may have to adjust the colors of one udg, but it is already acceptable for me as it is.

**Comment by NYYR1KK1** [comment]
It still looks I'm missing the custom characters and all of the characters outlooks are ROM defaults... The colors look fine though... The "problem" on this "SCREEN 1"-mode is that each 8-characters group have common background and foreground color. Another option is to use "SCREEN 2" where each line of each character may have own color, but it also means that you have to upload the character sets 3 times in order to cover whole screen. I think in this case it is indeed better to have multiple same looking characters with different colors.

![bug](https://user-images.githubusercontent.com/26676053/43939356-2c6f9b3e-9c72-11e8-9094-b2953225e3ab.png)

**Comment by NYYR1KK1** [comment]
(BTW I tested only ROM-version)

**Comment by Fabrizio-Caruso** [comment]
@NYYR1KK1 indeed only the rom version has this issue... I need to figure this out...
The .cas version is OK.

**Comment by Fabrizio-Caruso** [comment]
@NYYR1KK1 there was some problem with the Makefile entry that seems fixed now.
Could you please check it out?

https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/FULL_msx_32k.rom
https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/FULL_msx_32k.cas

**Comment by NYYR1KK1** [comment]
Yes, now it seems to work correctly. Thanks!

**Comment by Fabrizio-Caruso** [comment]
THANKS to you for testing!
